version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - Dom-R
  ignore:
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.12.0
    - 3.12.1
